### ISSUE TITLE
Encoded raddecs over 50001 not accepted

### ISSUE THREAD

**Issue by thomaskoerfer** [reelyactive/hlc-server#4]
I try to send raddecs from one remote device to a central device. On the remote device I'm running barnowl-hci and barnacles. On the central device I'm running hlc-server.

On the remote device I encode the raddec with encodeAsHexString() and send it over via dgram.

I found two issues, of which one seems blocking for me:
- the interpretation of an incoming raddec on hlc-server is done with toString('hex'), although I believe it should be done with toString('utf8'). I changed it on my codebase to get the import working
- as soon as I have the first raddec from the same transmitter (at least I believe this is the pattern), the determineNewPacket() method in barnacles.radecmanager fails. I manually set this to false because I'm not expecting new packet content

Even after tweaking above parts of the code, the hlc-server shows on the cover page that it is processing raddecs, but none of the other pages (e.g. Hello TLM Activity) shows any processed raddecs.

Would be great if someone could share experience sending over raddecs

**Comment by jeffyactive** [comment]
Hi @thomaskoerfer, thanks for raising the issue.

Typically, the remote device will run only barnowl (not barnacles) and forward the raddec stream.  For an example see our [tessel-edge code](https://github.com/reelyactive/tessel-edge).

Will take a look why the toString() conversion would need to be utf8 rather than hex and provide feedback on this thread.

The issue with the method in the barnacles raddecmanager failing is known, although at least one fix was made over the past months and the issue is rarely observed.  Will also take a look.

If the clocks on the remote and central devices are not well synchronised, it may be necessary to use the barnacles option "acceptStaleRaddecs": true.  Please advise if this corrects the issue in your case.

**Comment by thomaskoerfer** [comment]
Many thanks - this was super helpful. Some assumptions were simply wrong, which got clarified with the code example:
- re toString() - I didn't expect the hlc-server would expect an encoded Raddec transformed to a Binary hex. That is "Hex^2". Hence my assumption to convert it to utf-8 on the hlc-server end
- I didn't find it documented anywhere that the barnowl raddecs would need to be send over straight. Hence very helpful hint. I only wonder whether is network-friendly or whether that could be optimized
- Beaver on the hlc-server would only pick up the raddecs if I would switch on the options to include packets and timestamps. Something which I didn't get from the docu

After all - got everything working. Hence closing the issue
